name: 'Deploy'

on:
  pull_request:
    branches: [ "main", "develop" ]
    types: [closed]

jobs:
  terraform:
    name: 'Deploy Infra & App'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      APPLICATON_NAME: fiap-ml-models-monorepo
      OUTPUT_DIR: output
      MODELS_BUCKET_NAME: fiap-ml-models-monorepo-bucket

    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Echo Python Version
      shell: bash
      run: python --version

    - name: Current Working Directory
      run: pwd

    - name: Show Tree
      run: tree ../app

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Terraform Init
      run: terraform init -backend-config="key=$APPLICATON_NAME-${{ steps.extract_branch.outputs.branch }}.tfstate"

    - name: Terraform Plan
      run: terraform plan -var 'environment=${{ steps.extract_branch.outputs.branch }}' -var 'output_dir=$OUTPUT_DIR' -input=false

    - name: Install Python Packages
      run: | 
        cd .. 
        pip install -r requirements.txt

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var 'environment=${{ steps.extract_branch.outputs.branch }}' -var 'output_dir=$OUTPUT_DIR'

    - name: Create Pull Request to Main
      if: steps.extract_branch.outputs.branch == 'develop'
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: main